package errors;

public enum Errors {
	URL_LIMIT_EXCEEDED, NO_TARGET_FOUND, CONFIGURATION_NO_PROPERTY_FOUND, CUSTOM_CONFIGURATION_MISSING_VALUE, CUSTOM_CONFIGURATION_INCORRECT_FORMAT, CUSTOM_CONFIGURATION_NO_SUCH_PROPERTY, NO_SUCH_URL;

}
